import Header from "@/components/Header/header";
import "./globals.css";
import { Lato } from "next/font/google";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // choose weights you need
});

export const metadata = {
  title: "Dejargon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lato.className}>
      <body className="bg-primary">
        <main>{children}</main>
      </body>
    </html>
  );
}
