import Header from "@/components/Header/header";
import "./globals.css";
import { Lato } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // choose weights you need
});

export const metadata = {
  title: "Dejargon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen  bg-primary">
        {/* Header */}
        {/* <Header /> */}

        <div className="">
          {children}

          {/* Footer */}
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
